global:
    replay_buffer_size: 50000
    replay_buffer_episode: 2000

actor:
    num_actors: 1
    episodes_per_actor: 1000
    history_sample_prob: 0.2
    reward_scaling: 10.0

learner:
    model_pool_size: 2000
    lr: 0.0003
    epochs: 10
    batch_size: 8192
    mini_batch_size: 1024
    value_coeff: 0.1
    entropy_coeff: 0.01
    clip: 0.2                           # PPO gradient clipping
    dppo_clip: 3.0                      # DPPO gradient clipping
    grad_clip: 10.0                     # gradient norm clipping

    pretrained_ckpt_load_path: '/home/data4T1/lpy/rl-proj/pretrain/checkpoints'
    ckpt_save_interval: 10000           # in training iterations
    ckpt_save_path: '/home/data4T1/lpy/rl-proj/rl/checkpoints'
    log_interval: 500                   # in training iterations