global:
    replay_buffer_size: 50000
    replay_buffer_episode: 2000
    output_dir: /home/data4T1/lpy/rl-proj/rl/log/
    pretrained_model_path: '/home/data4T1/lpy/rl-proj/pretrain/log/20260111-121013/best.pt'

actor:
    num_actors: 200
    episodes_per_actor: 1000
    history_sample_prob: 0.2
    reward_scaling: 10.0
    gamma: 0.99
    lambda: 0.95

learner:
    model_pool_size: 100
    learning_rate: 0.00001 # 1e-5
    epochs: 10
    batch_size: 8192
    mini_batch_size: 1024
    warmup_learning_rate: 0.0003 # 3e-4
    warmup_iters: 5000

    value_coeff: 0.1
    entropy_coeff: 0.001
    clip: 0.2                           # PPO gradient clipping
    dppo_clip: 3.0                      # DPPO gradient clipping
    grad_clip: 1.0                     # gradient norm clipping

    ckpt_save_interval: 10000           # in training iterations
    log_interval: 500                   # in training iterations