epochs: 10
batch_size: 4096
learning_rate: 0.0003
weight_decay: 0.0001

num_channels: 256
num_blocks: 18

data_path: [/home/data4T1/lpy/rl-proj/pretrain/human-data/data.npz,
            /home/data4T1/lpy/rl-proj/pretrain/human-data/output2017/output2017_0.npz,
            /home/data4T1/lpy/rl-proj/pretrain/human-data/output2017/output2017_1.npz,
            /home/data4T1/lpy/rl-proj/pretrain/human-data/output2017/output2017_2.npz,
            /home/data4T1/lpy/rl-proj/pretrain/human-data/output2017/output2017_3.npz,
            /home/data4T1/lpy/rl-proj/pretrain/human-data/output2017/output2017_4.npz,
            /home/data4T1/lpy/rl-proj/pretrain/human-data/output2017/output2017_5.npz,
            /home/data4T1/lpy/rl-proj/pretrain/human-data/output2017/output2017_6.npz]
output_dir: /home/data4T1/lpy/rl-proj/pretrain/log
log_interval: 100